name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: bakenfazer/demo

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./react-express-mongodb/frontend
          file: ./react-express-mongodb/frontend/Dockerfile
          push: true
          tags: bakenfazer/demo:frontend
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./react-express-mongodb/backend
          file: ./react-express-mongodb/backend/Dockerfile
          push: true
          tags: bakenfazer/demo:backend
          labels: ${{ steps.meta.outputs.labels }}
